Bubble errors up to main() instead of panicking
In theory, all panics after this should be bugs instead of normal
error conditions.

The error reporting may still need finetuning. For example, if the
hostname doesn't resolve you get a redundant traceback:

```
Error: error sending request for url (http://bad-hostname/): error trying to connect: dns error: failed to lookup address information: Name or service not known

Caused by:
    0: error trying to connect: dns error: failed to lookup address information: Name or service not known
    1: dns error: failed to lookup address information: Name or service not known
    2: failed to lookup address information: Name or service not known
```

This commit also fixes all of the remaining Clippy warnings.

Resolves #14 (?)